const actionTypeConstants = {
    //locationModel
    REQUEST_LOCATION: 'REQUEST_LOCATION',
    RESPONSE_LOCATION: 'RESPONSE_LOCATION',
    LIST_LOCATION: 'LIST_LOCATION',
    CLEAR_LOCATION: 'CLEAR_LOCATION',
    SELECTED_LOCATION: 'SELECTED_LOCATION',
    REMOVE_SELECTED_LOCATION: 'REMOVE_SELECTED_LOCATION',

    REQUEST_SOLAR_SIZE: 'REQUEST_SOLAR_SIZE',
    RESPONSE_SOLAR_SIZE: 'RESPONSE_SOLAR_SIZE',
    SAVE_SOLAR_SIZE: 'SAVE_SOLAR_SIZE',
    CLEAR_SOLAR_SIZE: 'CLEAR_SOLAR_SIZE',

    REQUEST_USER: 'REQUEST_USER',
    RESPONSE_USER: 'RESPONSE_USER',
    SAVE_USER_DETAILS: 'SAVE_USER_DETAILS',
    CLEAR_USER_DETAILS: 'CLEAR_USER_DETAILS'
};

export default actionTypeConstants;
